services:
- docker
language: python
matrix:
  include:
  - python: '3.6'
before_install:
- pip install pip --upgrade
install:
- pip install yamllint
script:
- yamllint pb_nautobot_install.yml
- docker run --rm -i hadolint/hadolint < Dockerfile
- docker build -t networktocode/nautobot-lab:latest .
deploy:
  provider: script
  script: bash ./deploy/docker.sh
  on:
    branch: main
env:
  global:
  - secure: JEgqeiBMvjIJtoGkGks15Q2UhISRZSaeHzvdkStrBzJaVkxyFmzoR+FkpxufQhXBK3kQy1S+aor4AyTkK+Q6CGHvt+Ku93jk8vmL37PmM8uLPeecW7WjxBxtGJA9sxBFRdl2+pj+QO5ONTdRKwybmMQvYWcDWyFhnB3qpfEzCNboVEGQpPRs9hYaM6HbsjLvQK/CHeIZ5sIbWOo7sRYEDVBqwFJ8JpalldgjDOX2h9WHqmCYJIBe8Lw+4yYWIv9M+3GSfmrypvijT9HoJ9lSkYZ+4DByNALRzpKkZ7jnUapCodZjX372h+9lSOxgmA0q77kC2LxT1LSPSEmCwWCkvoeuHyZNZsZMLU1xXfaB5nC9c3iHFMUR+i2lsVHKg1IDyk68U3eqWJyXCjvGPHi1kQzkvgGs5WnlfAjlDU8hSgEsMPlaKTGuHCTfOrjqp5Nrv/Un+t2/bbUIQ9qeIBaTkjdqYfPedcH9u71e5HOh7v5sduClHkbJHmVU8+V7DENobZrs9yBNm6p9Igw8a8SeEjl3Ig0yK2m0txjUen46PDEMXpltp1NkcpokYT7dx+IBd57FUQhdvawPEF+FcWLEWL5fykTD48Pnx9YGxN/H7Fje+0HoVXyiU+dSfxcGbpIw5ZQNWbsd+CMHx3WDldAGhVNvfIxhD78Yzp8aR3tSg/I=
  - secure: YdWPZoyMkMKH+Oe5zsCx2c+VyCOzU7Ks0GZa9Ywc5fvp5HkOn9Yaw23KZHeBKNpvoL4R0DPj1ygbD2ROqpXc/KqSmSGf40zz1qNsk7LA4b+oMSSECZ0ytOEdErsp5X7HnzGHqDWhGzMsdBr+kQLqIwFTUmyChGzh6oLRLBFwuArRIrby88a25IZWfyhAHDVNkm/y1yDup3AGAi8dkrlm+sG0M574pKpK4ZcnGzULPlDRACqWK9hFhchWOwIBqWm8N4lthPwSoK/eYqHOwSM3IgKDM+1JGKlkDquHutMhZu6Oo0rkxWV8TiQ8MszcuZYDHlne1G1cQfMCyqbHlDw/mzdMYi+gvTH5ztiKQi9x2ut4ijs8jaqksZEZdzukpxkKBTiry9UhsH5X1uvi8Hq/ztTEHudU0eWwvyb5lXHwKNz23K86J4hMhkcxFWlDrruPMald6hth5ob+tU1YEOxE5MLvFES8EeUytCnevSjj271HYeB3Z413L2C1gfmTbF2E3XA5nK38XUoQrJqxjHPoMtcpqupgQMK/l8i8YeN+p4E3KzyjQpimK/fZyx75QY5L+1L6t1l8ToRYdVJC0WaQZioh9LRW8O49wtiKsOI+RXLmTa/sADY599lqbAgoiwvoF1Kw6epLyl6HMp+lBr1vTpbRupl2ja8Wf5vhRF46ORw=
